### ISSUE TITLE
Removing MonadWidget; and making example its own Cabal package

### ISSUE THREAD

**Issue by srid** [Atidot/reflex-codemirror#1]
Thanks for putting reflex-codemirror its own repo. I'm using this library in my project. It is currently a fork (forked before it was split here), and the two main changes I'd like to make are:

* Split the .cabal file into two, so that the app's reflex-utils dependency doesn't get in the way when using the library in Obelisk projects (for some reason cabal2nix needs executable dependencies as well). i.e., ./reflex-codemirror.cabal and ./example/example.cabal.
* Replace the now-deprecated `MonadWidget` with individual constraints.

If you'd be open to these changes, let me now. I can open them as separate PRs.

**Comment by barakber** [comment]
yeah sure sounds great
